image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
  - dotnet build lowlandtech.tinytools.sln
  except:
  - tags

test:
  stage: test
  script:
  - dotnet test lowlandtech.tinytools.sln
  except:
  - tags

release:
  stage: release
  script:
  - dotnet pack -c Release -p:PackageVersion=$CI_COMMIT_TAG
  - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
  - dotnet nuget add source "${NUGET_REGISTRY}" --name lowlandtech
  - dotnet nuget add source "${NUGET_REGISTRY_GITHUB}" --username "${NUGET_REGISTRY_GITHUB_USERNAME}" --password ${NUGET_REGISTRY_GITHUB_TOKEN} --store-password-in-clear-text --name github 
  - dotnet nuget push "src/*/bin/Release/*.nupkg" --source gitlab
  - dotnet nuget push "src/*/bin/Release/*.nupkg" --source lowlandtech -k "${NUGET_REGISTRY_KEY}"
  - dotnet nuget push "src/*/bin/Release/*.nupkg" --source github -k "${NUGET_REGISTRY_GITHUB_TOKEN}" --skip-duplicate
  - dotnet nuget push "src/*/bin/Release/*.nupkg" --source "https://api.nuget.org/v3/index.json" -k "${NUGET_REGISTRY_KEY}" --skip-duplicate
  only:
  - tags
